# Generated by Django 4.2 on 2025-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postcomment_post_alter_postcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts_tags', to='post.tag'),
        ),
    ]
