# Generated by Django 4.2 on 2025-03-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_created_at',
            new_name='date_joined',
        ),
    ]
