# Generated by Django 4.2 on 2025-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_created_at_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/profile.png', upload_to='profile_pics/'),
        ),
    ]
